// Generated by gencpp from file trigger_messages/MessageServerStarter.msg
// DO NOT EDIT!


#ifndef TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTER_H
#define TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTER_H

#include <ros/service_traits.h>


#include <trigger_messages/MessageServerStarterRequest.h>
#include <trigger_messages/MessageServerStarterResponse.h>


namespace trigger_messages
{

struct MessageServerStarter
{

typedef MessageServerStarterRequest Request;
typedef MessageServerStarterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MessageServerStarter
} // namespace trigger_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trigger_messages::MessageServerStarter > {
  static const char* value()
  {
    return "46763c709ef1bd75530a53ff3947f28e";
  }

  static const char* value(const ::trigger_messages::MessageServerStarter&) { return value(); }
};

template<>
struct DataType< ::trigger_messages::MessageServerStarter > {
  static const char* value()
  {
    return "trigger_messages/MessageServerStarter";
  }

  static const char* value(const ::trigger_messages::MessageServerStarter&) { return value(); }
};


// service_traits::MD5Sum< ::trigger_messages::MessageServerStarterRequest> should match 
// service_traits::MD5Sum< ::trigger_messages::MessageServerStarter > 
template<>
struct MD5Sum< ::trigger_messages::MessageServerStarterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trigger_messages::MessageServerStarter >::value();
  }
  static const char* value(const ::trigger_messages::MessageServerStarterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trigger_messages::MessageServerStarterRequest> should match 
// service_traits::DataType< ::trigger_messages::MessageServerStarter > 
template<>
struct DataType< ::trigger_messages::MessageServerStarterRequest>
{
  static const char* value()
  {
    return DataType< ::trigger_messages::MessageServerStarter >::value();
  }
  static const char* value(const ::trigger_messages::MessageServerStarterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trigger_messages::MessageServerStarterResponse> should match 
// service_traits::MD5Sum< ::trigger_messages::MessageServerStarter > 
template<>
struct MD5Sum< ::trigger_messages::MessageServerStarterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trigger_messages::MessageServerStarter >::value();
  }
  static const char* value(const ::trigger_messages::MessageServerStarterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trigger_messages::MessageServerStarterResponse> should match 
// service_traits::DataType< ::trigger_messages::MessageServerStarter > 
template<>
struct DataType< ::trigger_messages::MessageServerStarterResponse>
{
  static const char* value()
  {
    return DataType< ::trigger_messages::MessageServerStarter >::value();
  }
  static const char* value(const ::trigger_messages::MessageServerStarterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTER_H
