// Generated by gencpp from file trigger_messages/MessageServerRequest.msg
// DO NOT EDIT!


#ifndef TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERREQUEST_H
#define TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trigger_messages
{
template <class ContainerAllocator>
struct MessageServerRequest_
{
  typedef MessageServerRequest_<ContainerAllocator> Type;

  MessageServerRequest_()
    : switch_on(false)
    , device_name()  {
    }
  MessageServerRequest_(const ContainerAllocator& _alloc)
    : switch_on(false)
    , device_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _switch_on_type;
  _switch_on_type switch_on;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _device_name_type;
  _device_name_type device_name;





  typedef boost::shared_ptr< ::trigger_messages::MessageServerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trigger_messages::MessageServerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MessageServerRequest_

typedef ::trigger_messages::MessageServerRequest_<std::allocator<void> > MessageServerRequest;

typedef boost::shared_ptr< ::trigger_messages::MessageServerRequest > MessageServerRequestPtr;
typedef boost::shared_ptr< ::trigger_messages::MessageServerRequest const> MessageServerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trigger_messages::MessageServerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trigger_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trigger_messages::MessageServerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trigger_messages::MessageServerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trigger_messages::MessageServerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c60fbeed2e2b9ff81660371d10e5e5c";
  }

  static const char* value(const ::trigger_messages::MessageServerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c60fbeed2e2b9ffULL;
  static const uint64_t static_value2 = 0x81660371d10e5e5cULL;
};

template<class ContainerAllocator>
struct DataType< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trigger_messages/MessageServerRequest";
  }

  static const char* value(const ::trigger_messages::MessageServerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool switch_on\n\
string device_name\n\
";
  }

  static const char* value(const ::trigger_messages::MessageServerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.switch_on);
      stream.next(m.device_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MessageServerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trigger_messages::MessageServerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trigger_messages::MessageServerRequest_<ContainerAllocator>& v)
  {
    s << indent << "switch_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_on);
    s << indent << "device_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.device_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERREQUEST_H
