// Generated by gencpp from file trigger_messages/MessageServerStarterRequest.msg
// DO NOT EDIT!


#ifndef TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTERREQUEST_H
#define TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trigger_messages
{
template <class ContainerAllocator>
struct MessageServerStarterRequest_
{
  typedef MessageServerStarterRequest_<ContainerAllocator> Type;

  MessageServerStarterRequest_()
    : start(false)  {
    }
  MessageServerStarterRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;




  typedef boost::shared_ptr< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MessageServerStarterRequest_

typedef ::trigger_messages::MessageServerStarterRequest_<std::allocator<void> > MessageServerStarterRequest;

typedef boost::shared_ptr< ::trigger_messages::MessageServerStarterRequest > MessageServerStarterRequestPtr;
typedef boost::shared_ptr< ::trigger_messages::MessageServerStarterRequest const> MessageServerStarterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trigger_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trigger_messages/MessageServerStarterRequest";
  }

  static const char* value(const ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n\
";
  }

  static const char* value(const ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MessageServerStarterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trigger_messages::MessageServerStarterRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIGGER_MESSAGES_MESSAGE_MESSAGESERVERSTARTERREQUEST_H
